### ISSUE TITLE
缺少服务器推荐配置

### ISSUE THREAD

**Issue by LipYoung** [zhiyicx/thinkSNS-plus-help#1]
### 平台: 

- [x] 服务端

### 描述:

很多用户反馈希望知道TS+
推荐最低配置和 中等配置能支持的用户场景

**Comment by boxshadow** [comment]
TS+虽然统称是一个社交软件, 但是并非是我们在pc/手机上运行的软件或者app, 她对硬件的要求,需要用户量来衡量,并非像我们玩游戏一样, 需要哪种cpu,需要哪种显卡,或者是内存, 而是需要根据你有多少用户量, 日活, pv通过计算来推荐配置, 最低配置 1核cpu, 512的内存都可以跑起来, 只是对于运行环境才会有硬件要求, 比如,使用mysql5.7, mysql就会有强硬的限制: 至少需要1G的内存, 只需要满足这些必须依赖的软件,就可以流畅运行ts+, 多余用户量的量级很大的情况, 需要考虑专业的运维来做负载均衡,如果你的用户 1w以下, 4核8g + opcache, 如果附件较多, 建议使用第三方云存储, 这样可以降低购买服务器时绑定的带宽费用, 云存储其实很便宜
